name: Publish LXD image
on:
  push:
    #tags:

jobs:
  lxd:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: helloworld
    steps:
      -
          name: Checkout
          uses: actions/checkout@v2
      - # by https://github.com/docker/build-push-action/issues/37#issuecomment-720358308
        name: PrepareReg Names
        run: |
          echo REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV
      -
        name: install lxd
        run: |
          sudo snap install lxd
      -
        name: init lxd
        run: |
          sudo lxd init --auto
      
      - name: start ubuntu container
        run: | 
          sudo lxc launch ubuntu ubuntu
          sudo lxc config set ubuntu security.nesting 1

      - name: copy from repository to container
        run: |
          sudo lxc exec ubuntu -- mkdir /github-action
          sudo lxc file push -r ${{ github.workspace }}/* ubuntu/github-action
          sudo lxc exec ubuntu -- ls /
          sudo lxc exec ubuntu -- ls /github-action


      -
        name: test
        run: |
          pwd 

      -
        name: test
        run: |
          ls
      -
        name: test
        run: |
          docker info





